### ISSUE TITLE
Python error when pulling up placeholder registration list

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#186]
On this page from the road map

Registration -> Placeholders

https://reg.furfest.org/rams/registration/placeholders

Throwing the following python error:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/site_sections/registration.py", line 895, in placeholders
    'checklist': session.checklist_status('placeholders', department),
  File "/app/plugins/uber/uber/models.py", line 553, in checklist_status
    raise ValueError("Can't access dept checklist INI settings for section '{}', check your INI file".format(slug))
ValueError: Can't access dept checklist INI settings for section 'placeholders', check your INI file

**Comment by kitsuta** [comment]
Oh, that's a strange requirement. It's expecting some config options. From the MAGFest puppet file:
```
  placeholders:
    name: "Checking Placeholder Registrations"
    deadline: "2017-11-22"
    description: "We create placeholder registrations for volunteers and ask them to fill out the rest of their information and also confirm that they'll be coming.  We need our department heads to review the unclaimed badges for their departments to check for any essential volunteers who haven't claimed their badges."
    path: "/registration/placeholders?department={department}"
```
